version: '3'

services:
  expo-dev:
    build: .
    container_name: expo-dev
    volumes:
      - ./app:/app
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true