name: Build Docker Containers

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-postgres:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build PostgreSQL container
        uses: docker/build-push-action@v4
        with:
          context: ./docker_postgre
          push: false
          tags: local/postgres-postgis:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install Trivy
        uses: aquasecurity/trivy-action@v0.18.0

      - name: Scan PostgreSQL container with Trivy
        run: trivy image --exit-code 1 --severity HIGH,CRITICAL local/postgres-postgis:latest

  build-python-flask:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Python Flask container
        uses: docker/build-push-action@v4
        with:
          context: ./python_flask_docker
          push: false
          tags: local/python-flask:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install Trivy
        uses: aquasecurity/trivy-action@v0.18.0

      - name: Scan Python Flask container with Trivy
        run: trivy image --exit-code 1 --severity HIGH,CRITICAL local/python-flask:latest

  build-java8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Java 8 container
        uses: docker/build-push-action@v4
        with:
          context: ./java_authentication_docker
          push: false
          tags: local/java8-spring:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install Trivy
        uses: aquasecurity/trivy-action@v0.18.0

      - name: Scan Java 8 container with Trivy
        run: trivy image --exit-code 1 --severity HIGH,CRITICAL local/java8-spring:latest

  build-java21:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Java 21 container
        uses: docker/build-push-action@v4
        with:
          context: ./java_location_docker
          push: false
          tags: local/java21-spring:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install Trivy
        uses: aquasecurity/trivy-action@v0.18.0

      - name: Scan Java 21 container with Trivy
        run: trivy image --exit-code 1 --severity HIGH,CRITICAL local/java21-spring:latest